
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


import { Metadata, BaseRepository } from "@hiveops/core";
import { Person } from "./person";


export type AdminData = Person & {
  adminSince: Date;
  permissions: Array<string>;
};

export type Admin = Metadata & AdminData;

export class AdminRepository extends BaseRepository<AdminData, Admin> {
  constructor() {
    super("Admin");
  }
}

export const adminRepository = new AdminRepository();