
/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


import { Metadata } from "@hiveops/core";
import { BaseRepository } from "@hiveops/node";


export type AreaData = {
  countries: string;
  refs: string;
  state: string;
};

export type Area = Metadata & AreaData;

export class AreaRepository extends BaseRepository<AreaData, Area> {
  constructor() {
    super("Area");
  }
}

export const areaRepository = new AreaRepository();