/**
* This code is generated by Vespa.
* Do not edit this file directly.
* Instead, make changes to the *.hsl files and regenerate the code.
* See the Vespa documentation for more information.
*/


import { initialize } from "@hiveops/core";
import { PostRepository } from "./post";
import { UserRepository } from "./user";


export const postRepository = new PostRepository();
export const userRepository = new UserRepository();

export const vespaInit = (options?: {
  stackHRN: string;
  accessToken: string;
}): void => {
  initialize(options);
};