/**
 * This code is generated by Vespa.
 * Do not edit this file directly.
 * Instead, make changes to the *.hsl files and regenerate the code.
 * See the Vespa documentation for more information.
 */

import { ColumnType, Metadata } from "@hiveops/core";
import { BaseRepository } from "@hiveops/node";
import { Image } from "./image";
import { Person } from "./person";

export type UserData = Person & {
  email: string;
  role: string;
  isActive: boolean;
  lastLogin: Date;
  profileImage: Image;
};

export type User = Metadata & UserData;

export class UserRepository extends BaseRepository<UserData, User> {
  constructor() {
    super("User", {
      firstName: ColumnType.TEXT,
      lastName: ColumnType.TEXT,
      email: ColumnType.TEXT,
      age: ColumnType.INTEGER,
      profileImage: ColumnType.TEXT,
    });
  }
}
